
## Static graph (TensorFlow 1.x) vs Eager execution (TensorFlow 2.0)

![alt text](https://www.tensorflow.org/images/tensors_flowing.gif)
*Image take from: https://www.tensorflow.org/guide/graphs*


## TensorFlow 1.X




### Installing TensorFlow 1.X



In [28]:
!pip uninstall tensorflow

In [3]:
!pip install tensorflow-gpu==1.13.1

     |████████████████████████████████| 345.0 MB 3.4 kB/s 
     |████████████████████████████████| 3.2 MB 44.9 MB/s 
     |████████████████████████████████| 367 kB 80.2 MB/s 
     |████████████████████████████████| 50 kB 7.1 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.6.0
    Uninstalling tensorflow-estimator-2.6.0:
      Successfully uninstalled tensorflow-estimator-2.6.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.6.0
    Uninstalling tensorboard-2.6.0:
      Successfully uninstalled tensorboard-2.6.0


In [5]:
import tensorflow as tf

In [6]:
tf.__version__

'1.13.1'

### Variables and constants in TF 1.x

#### Variables

In [7]:
#Initialize normal Variable in tf 1.x
variable = tf.Variable([[30, 20], [10, 45]])

Instructions for updating:
Colocations handled automatically by placer.


In [8]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [9]:
#Getting shape of the variable
variable.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [10]:
#Performing addition operation on the tensor produces another tf.Tensor object
variable + 2

<tf.Tensor 'add:0' shape=(2, 2) dtype=int32>

In [12]:
#If a session is not initialized we cannot access values in the Variable/Tensor
# Session이 없을 경우 값을 출력할 수 없음. tensorflow 1.0의 특징
variable.eval()

ValueError: ignored

In [13]:
#Able to slice a variable, but we are still not able to retrive values from it
variable[:1]

<tf.Tensor 'strided_slice:0' shape=(1, 2) dtype=int32>

#### Getting values from variables

In [14]:
#Initialize session
session = tf.Session()

In [15]:
#Initialize ALL variables for the session
session.run(tf.global_variables_initializer())

In [16]:
#Run the eval method on the evironment with provided session to retrive values from it
variable.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

#### Constants/Tensors

In [17]:
#Define a TensorFlow constant matrix
tensor = tf.constant([[23, 4], [32, 51]])

In [18]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [19]:
#We are still not able to get the real value without defining a session
tensor.eval()

ValueError: ignored

#### Getting values from constants

In [20]:
session = tf.Session()

In [21]:
session.run(tf.global_variables_initializer())

In [22]:
#Fatching the tensor from the tensor graph/session
tensor_value = session.run(tensor)

In [23]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

## TensorFlow 2.0

### Installing TensorFlow 2.0

In [30]:
!pip uninstall tensorflow-gpu
!pip install tensorflow-gpu==2.3.0

Found existing installation: tensorflow-gpu 2.3.0
Uninstalling tensorflow-gpu-2.3.0:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.7/dist-packages/tensorflow/*
    /usr/local/lib/python3.7/dist-packages/tensorflow_gpu-2.3.0.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled tensorflow-gpu-2.3.0
  Using cached tensorflow_gpu-2.3.0-cp37-cp37m-manylinux2010_x86_64.whl (320.4 MB)


In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.3.0'

### Constants/Tensors

In [3]:
#Defining a constant in TensorFlow 2.0
tensor_20 = tf.constant([[23,12], [32,0]])

In [4]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23, 12],
       [32,  0]], dtype=int32)>

In [5]:
#Getting shape of a tensor
tensor_20.shape

TensorShape([2, 2])

### Getting values from constants

In [6]:
#Getting values straight from a TensorFlow constant to numpy - without sesion
tensor_20.numpy()

array([[23, 12],
       [32,  0]], dtype=int32)

In [7]:
#We are able to convert a numpy matrix back to a TensorFlow tensor as well
numpy_tensor = np.array([[23,  4], [32, 51]])

In [8]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [9]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Operations with constants/tensors

In [10]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Addition between scalar and tensor

In [11]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplication between scalar and tensor

In [12]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Using Numpy functions on TensorFlow tensors

In [13]:
#Squaring all numbers in a tensorflow tensor object
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [14]:
#Square root of all numbers in a tensorflow tensor object
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Dot product between two tensors

In [16]:
 # inner product
 np.dot(tensor, tensor_20)

array([[ 87,  12],
       [197,  36]], dtype=int32)

### Operations with variables

In [17]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Getting raw value from the variable

In [18]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Changing specific value in the TensorFlow variable

In [21]:
# 0, 2 position에 100 어싸인.
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [22]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Strings in TensorFlow 2.0

In [23]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

#### Simple string operations

In [24]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [25]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

### Storing arrays of strings

In [26]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [27]:
tf_string_array

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'TensorFlow', b'Deep Learning', b'AI'], dtype=object)>

In [28]:
#How to iterate through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)


### Handling Devices in TensorFlow 2.0

#### CPU

In [29]:
with tf.device("/cpu:0"):
    tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [30]:
tf_string_array.device

'/job:localhost/replica:0/task:0/device:CPU:0'

#### GPU

In [31]:
if tf.test.is_gpu_available():
    with tf.device("/gpu:0"):
        tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])
    print(tf_string_array.device)

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
