In [38]:
import numpy as np
import pandas as pd
#np.array([1,2,3])
#np.ones([3,4])
#np.empty([3,4])

data = np.array([[2,4,5], [4,5,6]])
data

array([[2, 4, 5],
       [4, 5, 6]])

In [22]:
# newest matrix access method
data[1,2]

6

In [23]:
# slicing 
data[0, 1:3]

array([4, 5])

In [24]:
# Call by ref
data2 = data[0, 1:3]
data[0, 1:3] = [99, 98]
data
data2

array([99, 98])

In [25]:
# So, we need to memcpy
data3 = data[1, 1:2].copy()
data[1, 1:2] = 30
data3

array([5])

In [28]:
ser = pd.Series([2,4,6,8])
ser

0    2
1    4
2    6
3    8
dtype: int64

In [30]:
# custom indexing... omg..
ser = pd.Series([2,4,6,8], index=['a','b','c','d'])
ser

a    2
b    4
c    6
d    8
dtype: int64

In [33]:
# Slicing pandas Series
ser[2:]

c    6
d    8
dtype: int64

In [39]:
values = {
    "aa": [1,2,3],
    "bb": ["a","b","c"]
}
values

{'aa': [1, 2, 3], 'bb': ['a', 'b', 'c']}

In [41]:
df = pd.DataFrame(values)
df

aa bb
0   1  a
1   2  b
2   3  c

In [45]:
# dataframe indexing
# using dictionary
values1 = {
    "aa":{'a':1, 'b':2, 'c':3},
    "bb":{0:4, 1:5, 2:6}
}
df1 = pd.DataFrame(values1)
df1

aa   bb
a  1.0  NaN
b  2.0  NaN
c  3.0  NaN
0  NaN  4.0
1  NaN  5.0
2  NaN  6.0

In [52]:
# using numpy array
df2 = pd.DataFrame(np.arange(6).reshape(3,2), index=["a", "b", "c"], columns=["aa","bb"])
np.arange(6).reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [53]:
df2

aa  bb
a   0   1
b   2   3
c   4   5